fragment RepositoryFields on Repository {
  githubId
  createdAt
  pushedAt
  url
  forkCount
  isArchived
  name
  releasesCount
  stargazerCount
  languages {
    totalCount
    totalSize
    nodes {
      id
      size
    }
  }
}

query User($login: String!) {
  user(login: $login) {
    githubId
    githubFetchedAt
    githubServiceFetchedAt
    login
    avatarUrl
    location
    followersCount
    ownedStars
    contributedStars
    company
    email
    followingCount
    githubCreatedAt
    isHireable
    name
    twitterUsername
    websiteUrl
    firstSeenAt
    repositoriesCount
    contributedRepoCount
    fetchingStatus
    fetchingUpdatedAt
    socialAccounts {
      totalCount
      nodes {
        displayName
        provider
        url
      }
    }
    organizations {
      githubId
      login
      avatarUrl
      name
    }
    contributions {
      year
      prsCount
      mergedPrsCount
      linesAdded
      linesRemoved
      repository {
        ...RepositoryFields
      }
    }
    repositories {
      ...RepositoryFields
    }
    timeline {
      changes
      createdAt
    }
    rank {
      ownedStars
      ownedStarsProvisional
      ownedStarsM
      ownedStarsY
      contributedStars
      contributedStarsProvisional
      contributedStarsM
      contributedStarsY
      followersCount
      followersCountProvisional
      followersCountM
      followersCountY
    }
  }
}
