query TopRanks {
  byStars: rankings(order: STARS) {
    user {
      login
    }
  }
  byContribution: rankings(order: CONTRIBUTIONS) {
    user {
      login
    }
  }
  byFollowers: rankings(order: FOLLOWERS) {
    user {
      login
    }
  }
}
