query RankByLogin($login: String!) {
  rankByLogin(login: $login) {
    githubId
    contributedStars
    contributedStarsM
    followersCount
    followersCountM
    ownedStars
    ownedStarsM
    user {
      login
      avatarUrl
      ownedStars
      contributedStars
      followersCount
      location
    }
  }
}
