fragment UserBaseFields on User {
  githubId
  login
  name
  avatarUrl
  location
  country
  countryFlag
  company
  email
  f
  followingCount
  githubCreatedAt
  githubFetchedAt
  websiteUrl
  socialAccounts {
    totalCount
    nodes {
      displayName
      provider
      url
    }
  }
  organizations {
    login
    avatarUrl
    name
  }
}
