query CountryRankByLogin($login: String!) {
  countryRankByLogin(login: $login) {
    githubId
    c
    cM
    f
    fM
    s
    sM
    country
    user {
      login
      avatarUrl
      s
      c
      f
      location
    }
  }
}
