query CountryLanguageSummary($country: String!, $order: LanguageSummaryOrder, $offset: Int = 0, $limit: Int = 24) {
  countryLanguageSummary(order: $order, offset: $offset, limit: $limit, country: $country) {
    language
    country
    date
    usersCount
    score
    size
    topUser {
      login
      avatarUrl
      country
    }
    languageData {
      color
    }
  }
}
