query GlobalRankings($order: RankOrder, $offset: Int) {
  globalRankings(order: $order, offset: $offset) {
    githubId
    c
    cM
    f
    fM
    s
    sM
    user {
      login
      avatarUrl
      s
      c
      f
      location
    }
  }
}
