query PageProfileOverview($login: String!, $isGlobalContext: Boolean! = true) {
  user(login: $login) {
    firstSeenAt
    ...UserBaseFields
    ...UserFetchingStatus
    ...UserSeo
    ...UserTiersGlobal @include(if: $isGlobalContext)
    ...UserTiersCountry @skip(if: $isGlobalContext)
    rankGlobal @include(if: $isGlobalContext) {
      s
      sProvisional
      sM
      c
      cProvisional
      cM
      f
      fProvisional
      fM
    }
    rankCountry @skip(if: $isGlobalContext) {
      s
      sProvisional
      sM
      c
      cProvisional
      cM
      f
      fProvisional
      fM
    }
    sLangs(limit: 4) {
      name
      color
      size
      score
      sources {
        name
        stargazerCount
        percentage
        year
      }
    }
    cLangs(limit: 4) {
      name
      color
      size
      sources {
        name
        stargazerCount
        percentage
        year
        linesAdded
        linesRemoved
        prsCount
        url
      }
    }
    snapshots
    repositories(limit: 5) {
      ...RepositoryFields
    }
    contributions(limit: 5) {
      ...ContributionFields
    }
    timeline(limit: 5) {
      changes
      createdAt
    }
  }
}
