query ProfileOverview($login: String!, $rankGlobal: Boolean! = true) {
  user(login: $login) {
    ...UserBaseFields
    ...UserFetchingStatus
    ...UserSeo
    ...UserGlobalTiers @include(if: $rankGlobal)
    ...UserCountryTiers @skip(if: $rankGlobal)
    rankGlobal @include(if: $rankGlobal) {
      s
      sProvisional
      sM
      c
      cProvisional
      cM
      f
      fProvisional
      fM
    }
    rankCountry @skip(if: $rankGlobal) {
      s
      sProvisional
      sM
      c
      cProvisional
      cM
      f
      fProvisional
      fM
    }
    languages(limit: 3) {
      name
      color
      size
      score
      # rankGlobal @include(if: $rankGlobal) {
      #   s
      # }
      # tiersGlobal @include(if: $rankGlobal) {
      #   sTiers {
      #     ...TierFields
      #   }
      #   sUsers
      # }
      # rankCountry @skip(if: $rankGlobal) {
      #   s
      # }
      # tiersCountry @skip(if: $rankGlobal) {
      #   sTiers {
      #     ...TierFields
      #   }
      #   sUsers
      # }
    }
  }
}
