query ProfileSummary($login: String!) {
  user(login: $login) {
    githubId
    githubFetchedAt
    githubServiceFetchedAt
    login
    avatarUrl
    location
    country
    f
    s
    c
    company
    email
    followingCount
    githubCreatedAt
    isHireable
    name
    twitterUsername
    websiteUrl
    firstSeenAt
    contributedRepoCount
    fetchingStatus
    fetchingUpdatedAt
    socialAccounts {
      totalCount
      nodes {
        displayName
        provider
        url
      }
    }
    organizations {
      login
      avatarUrl
      name
    }
    rankGlobal {
      s
      sProvisional
      sM
      c
      cProvisional
      cM
      f
      fProvisional
      fM
    }
    rankCountry {
      s
      sProvisional
      sM
      c
      cProvisional
      cM
      f
      fProvisional
      fM
    }
  }
}
