query ProfileRepositories($login: String!, $offset: Int, $limit: Int) {
  user(login: $login) {
    repositoriesCount
    repositories(offset: $offset, limit: $limit) {
      ...RepositoryFields
    }
  }
}
