query RankTiersByName($name: String!) {
  rankTiersByName(name: $name) {
    sUsers
    cUsers
    fUsers
    sTiers {
      tier
      level
      minRank
      maxRank
      minValue
    }
    fTiers {
      tier
      level
      minRank
      maxRank
      minValue
    }
    cTiers {
      tier
      level
      minRank
      maxRank
      minValue
    }
  }
}
