query TopGlobalRankings {
  byStars: globalRankings(order: STARS) {
    user {
      login
    }
  }
  byContribution: globalRankings(order: CONTRIBUTIONS) {
    user {
      login
    }
  }
  byFollowers: globalRankings(order: FOLLOWERS) {
    user {
      login
    }
  }
}
